name: tenon
services:
- name: backend-api
  project: Backend/Api/Hosts/Tenon.Backend.Api.Hosts.csproj
  bindings:
  - port: 7000
- name: postgres-api
  image: postgres:latest
  connectionString: "Host=${host}:${port};Database=tenon;Username=superuser;Password=Test123456"
  env:
  - name: POSTGRES_PASSWORD
    value: Test123456
  - name: POSTGRES_DB
    value: tenon
  - name: POSTGRES_USER
    value: tenonuser